shared:
  image: golang
  environment:
    GOPATH: /sd/workspace
    GO111MODULE: on

jobs:
  A:
    requires: [ ~commit ]
    steps:
      - rm: rm /opt/sd/store-cli
      - get: go get github.com/screwdriver-cd/store-cli
      - touch: echo test > "$SD_ARTIFACTS_DIR/this file name includes space (test)"

