shared:
  image: golang
  environment:
    GOPATH: /sd/workspace
    GO111MODULE: on

jobs:
  A:
    requires: [ ~commit ]
    steps:
      - get: go get github.com/screwdriver-cd/store-cli; cp $(command -v store-cli) /opt/sd/store-cli
      - touch: echo test > "$SD_ARTIFACTS_DIR/this file name includes space (test)"

